### ISSUE TITLE
Close this organisation

### ISSUE THREAD

**Issue by lobingera** [JuliaPlot/juliaplot_docs#11]
This (JuliaPlot) is around for some time without contributions and some people have found better places to develop https://github.com/JuliaGraphics/ and https://github.com/JuliaPlots/
I have already removed my juliaplot_interact text (only contributor).
@waldyrious @Sisyphuss @tbreloff Please check re-use.

**Comment by tbreloff** [comment]
+1 to closing.  This org served its purpose a year ago, and there's no good reason to keep it around.

**Comment by waldyrious** [comment]
👍 from me.

**Comment by Sisyphuss** [comment]
OK.

**Comment by waldyrious** [comment]
Ok, given that [all authors of content currently in the repo](https://github.com/JuliaPlot/juliaplot_docs/graphs/contributors) have agreed, I'll close the org.
