### ISSUE TITLE
Should graph visualization packages be included?

### ISSUE THREAD

**Issue by waldyrious** [JuliaPlot/juliaplot_docs#3]
I'm nor sure if they are considered in the same class of plotting packages, but intuitively they seem to be at least related.

This would include [GraphViz.jl](https://github.com/Keno/GraphViz.jl), [TikzGraphs.jl](https://github.com/sisl/TikzGraphs.jl) and [GraphLayout.jl](https://github.com/IainNZ/GraphLayout.jl) (and maybe others).

**Comment by wildart** [comment]
Why not? It would be nice to see some integration with plotting packages down the road.

**Comment by lobingera** [comment]
+1
Technically graph visualisations are just another 2D line plot with labels.

**Comment by waldyrious** [comment]
If there's another +1 with no opposition, I'll add them to the readme :)

**Comment by tbreloff** [comment]
+1
