### ISSUE TITLE
Plots.jl documentation

### ISSUE THREAD

**Issue by tbreloff** [JuliaPlot/juliaplot_docs#8]
Hi all... I'm making pretty good progress on my [Plots.jl](https://github.com/tbreloff/Plots.jl) package, and I'd like to start compiling examples with pictures with documentation.  For those that have done documentation for other packages... what is your toolset?  Are there good tools to be able to run julia code within markdown?  I know of Judo.jl, but I'm not 100% sure I understand how to use it fully.  Any advice?

Right now, you can get a lot of plotting functionality for Qwt.jl and Gadfly.jl with the same interface, and as I add additional packages it will be very important that I automatically generate the example results for each supported package (all you have to do is call `plotter!(:gadfly)` to switch, then all commands are converted into Gadfly calls).  I don't want it to be a manual process... I'll write the md/html generation myself if I have to.

**Comment by Evizero** [comment]
Well you could use Rmd with a custom Julia engine. Here is a Rmd file I hacked together. You should pre-compile Gadfly though, because every code block will execute a separate Julia instance

The following .Rmd file

    ---
    title: "Julia Markdown"
    author: "Christof Stocker"
    date: "September 10, 2015"
    output: 
      html_document: 
        keep_md: yes
    ---
    
    ```{r, include=FALSE}
    library(knitr)
    eng_julia <- function(options) {
      plot.cmd <- if(options$fig.path != "" && options$fig.env != "") {
        paste0("draw(PNG(\"", options$fig.path,"\", 4inch, 3inch), ", options$fig.env,")")
      } else ""
      plot.inc <- if(options$fig.path != "" && options$fig.env != "") {
        paste0("![](", options$fig.path,")")
      } else ""
      code <- paste("-E", shQuote(paste(options$engine.opts, 
                                        paste(options$code, collapse = '\n'), 
                                        plot.cmd, 
                                        sep = "\n")))
      cmd <- paste0(options$engine.path, "julia")
      out <- if (options$eval) {
        message('running: ', cmd, ' ', code)
        tryCatch(system2(cmd, code, stdout = TRUE, stderr = TRUE), error = function(e) {
          if (!options$error) stop(e)
          paste('Error in running command', cmd)
        })
      } else ''
      if (!options$error && !is.null(attr(out, 'status')))
        stop(paste(out, collapse = '\n'))
      paste(knitr::engine_output(options, options$code, out), plot.inc, sep = "\n")
    }
    knitr::knit_engines$set(julia = eng_julia)
    ```
    
    This is my **markdown document**
    
    ```{julia, results='hide', fig.env="mp", fig.path="myplot.png", engine.opts="using Gadfly"}
    mp = plot(x=rand(10), y=rand(10))
    ```

produces the following .md file

    # Julia Markdown
    Christof Stocker  
    September 10, 2015  
    
    This is my **markdown document**
    
    ```julia
    mp = plot(x=rand(10), y=rand(10))
    ```
    
    ![](myplot.png)

**Comment by tbreloff** [comment]
I decided to throw together my own markdown generator... turned out to be pretty easy.  (yay julia)  See: https://github.com/tbreloff/Plots.jl/tree/master/docs
