### ISSUE TITLE
"Build plot in pieces" differs?

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaPlot/juliaplot_docs#9]
For the "build plot in pieces" examples, the line styles differ:
one is a line per se, one is a boundary to fill below.
(if that is how the two pkgs plot, nevermind).

**Comment by tbreloff** [comment]
I couldn't find a `:sticks` equivalent in Gadfly, so I chose to do that.  Also, you should open issues in Plots.jl, not here.
